### ISSUE TITLE
Deploying Python Apps

### ISSUE THREAD

**Issue by lanbau** [alyssaq/python-data-science-intro#2]
Hi Alyssa! i have managed to setup localhost & display the matplotlib results on to HTML using flask.

![screen shot 2016-01-08 at 10 12 37 am](https://cloud.githubusercontent.com/assets/5410693/12188446/62cc6e34-b5f0-11e5-87dc-c40a5e485610.jpg)

Is there a recommended way to deploy python apps to heroku or any hosting platforms?

**Comment by alyssaq** [comment]
Hi!

Great work getting the graphs displayed with flask!
I usually deploy to heroku or AWS EC2 (paid).
Theres also [pythonanywhere](https://www.pythonanywhere.com) but I havent used it before.

**Comment by lanbau** [comment]
awesome. just managed to deploy pandas on heroku after a morning of errors.

thanks alyssa for the python codes!

if anyone's interested...
here's the link: [https://app-helloflask1.herokuapp.com/]
github project: [https://github.com/lanbau/helloflask1]

**Comment by alyssaq** [comment]
:+1:
